friends = ('Max', 'Joseph', 'Faiz', 'Suhaib')
msg = "Hello " + friends[0].title()
msg2 = "Hello " + friends[1].title()
msg3 = "Hello " + friends[2].title()
msg4 = "Hello " + friends[3].title()
print(msg)
print(msg2)
print(msg3)
print(msg4)
#print(friends[0].title())
#print(friends[1].title())
#print(friends[2].title())
#print(friends[3].title())